version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './my-app'
      - '/my-app/node_modules'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FLASK_RUN_PORT=8080

    ports:
      - 8080:8080