version: "3.7"
services:
  app:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=backend
      - FLASK_RUN_PORT=8000

    ports:
      - 8000:8000